import { Project } from "@/app/_types/types";

export const taskmasterAI: Project = {
  id: "taskmaster-ai-productivity-platform",
  title: "TaskMaster AI – Intelligent Task & Note Management Platform",
  description: {
    en: "An AI-powered productivity platform combining advanced task management, habit tracking, intelligent notes, and automation through a scalable backend API and a modern frontend application.",
    ar: "منصة إنتاجية مدعومة بالذكاء الاصطناعي تجمع بين إدارة المهام المتقدمة، تتبع العادات، الملاحظات الذكية، والأتمتة عبر واجهة خلفية قوية وتطبيق واجهة أمامية حديث.",
  },
  fullDescription: {
    en: "TaskMaster AI is a full-stack, enterprise-grade productivity platform designed to go beyond traditional to-do applications. It provides intelligent task management with dependencies, subtasks, recurring habits, and analytics, alongside a powerful note system with rich editing and AI-assisted processing. The backend is built with Node.js, TypeScript, and MongoDB, exposing a robust REST API with automation, notifications, and Google Gemini AI integration. The frontend is developed using Next.js 15 and React 19, offering multiple task visualizations, a Notion-like editor, deep AI integration, and a highly customizable theming system.",
    ar: "TaskMaster AI هو نظام إنتاجية متكامل (Full-Stack) مصمم لتجاوز تطبيقات المهام التقليدية. يوفر إدارة ذكية للمهام تشمل الاعتماديات، المهام الفرعية، العادات المتكررة، والتحليلات، إلى جانب نظام ملاحظات قوي مع محرر غني ودعم الذكاء الاصطناعي. تم بناء الواجهة الخلفية باستخدام Node.js و TypeScript و MongoDB مع واجهة REST API متقدمة تدعم الأتمتة، الإشعارات، وتكامل Google Gemini AI. أما الواجهة الأمامية فهي مطورة باستخدام Next.js 15 و React 19، وتقدم طرق عرض متعددة للمهام، محررًا شبيهًا بـ Notion، تكاملًا عميقًا مع الذكاء الاصطناعي، ونظام تخصيص شامل للمظهر.",
  },
  image: "/projects/taskmaster/4.png",
  technologies: [
    "Next.js 15",
    "React 19",
    "TypeScript",
    "Node.js",
    "Express.js",
    "MongoDB",
    "Mongoose",
    "Tailwind CSS",
    "Shadcn/UI",
    "TanStack Query",
    "Framer Motion",
    "D3.js",
    "Tiptap",
    "Google Gemini AI",
    "Telegram Bot API",
    "Nodemailer",
    "node-cron",
  ],
  liveUrl: undefined,
  githubUrl: {
    frontend: "https://github.com/Abdelaziz79/task-master-frontend",
    backend: "https://github.com/Abdelaziz79/task-master-backend",
  },
  team: {
    en: "Individual Project",
    ar: "مشروع فردي",
  },
  duration: {
    en: "Ongoing / Actively Developed",
    ar: "قيد التطوير والتحسين المستمر",
  },
  features: {
    en: [
      "Advanced task management with subtasks, dependencies, priorities, and due dates",
      "Habit tracking system with recurrence patterns, streaks, and analytics",
      "Intelligent note-taking system with a Notion-like rich text editor",
      "AI-powered task generation, classification, breakdown, and scheduling",
      "AI-assisted note summarization, formatting, tagging, and content generation",
      "Multiple task views: List, Calendar, Timeline (Gantt-style), and Graph view",
      "Telegram bot integration for managing tasks and notes via chat commands",
      "Email notifications for reminders, summaries, and system alerts",
      "Automated cron jobs for reminders, summaries, and maintenance tasks",
      "Public sharing and cloning of tasks and notes with unique URLs",
      "Highly customizable UI with theme system and dark/light mode support",
      "Secure JWT-based authentication with role-based access control",
    ],
    ar: [
      "إدارة مهام متقدمة مع المهام الفرعية، الاعتماديات، الأولويات، وتواريخ الاستحقاق",
      "نظام تتبع العادات مع أنماط تكرار، سلاسل إنجاز، وتحليلات أداء",
      "نظام ملاحظات ذكي مع محرر نصوص غني شبيه بـ Notion",
      "إنشاء المهام وتصنيفها وتقسيمها وجدولتها باستخدام الذكاء الاصطناعي",
      "تحسين ومعالجة الملاحظات بالذكاء الاصطناعي (تلخيص، تنسيق، اقتراح وسوم)",
      "طرق عرض متعددة للمهام: قائمة، تقويم، مخطط زمني، وعرض بياني",
      "تكامل بوت تيليجرام لإدارة المهام والملاحظات عبر الأوامر",
      "إشعارات بريد إلكتروني للتذكير والملخصات والتنبيهات",
      "مهام مجدولة تلقائيًا (Cron Jobs) للتذكير والصيانة",
      "مشاركة عامة واستنساخ المهام والملاحظات عبر روابط فريدة",
      "واجهة مستخدم قابلة للتخصيص مع دعم الوضع الفاتح والمظلم",
      "نظام مصادقة آمن باستخدام JWT مع صلاحيات متعددة",
    ],
  },
  screenshots: [
    "/projects/taskmaster/1.png",
    "/projects/taskmaster/2.png",
    "/projects/taskmaster/3.png",
    "/projects/taskmaster/4.png",
    "/projects/taskmaster/5.png",
    "/projects/taskmaster/6.png",
    "/projects/taskmaster/7.png",
    "/projects/taskmaster/8.png",
    "/projects/taskmaster/9.png",
    "/projects/taskmaster/10.png",
    "/projects/taskmaster/11.png",
    "/projects/taskmaster/12.png",
    "/projects/taskmaster/13.png",
  ],
};
